# myfirstrobot:
#   # Publish all joint states -----------------------------------
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50  

#   # Position Controllers ---------------------------------------
#   joint1_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint1
#     pid: {p: 20.0, i: 0.01, d: 10.0}
#   joint2_position_controller:
#     type: effort_controllers/JointPositionController
#     joint: joint2
#     pid: {p: 20.0, i: 0.01, d: 10.0}

myfirstrobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 120.0, i: 10.01, d: 20.0}

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: my_controller_pkg/MyControllerClass
    joint_name: joint1